force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>Log file for custom APEX code to log to</description>
    <label>System Log</label>
    <nameField>
        <label>System Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Log__c/fields/Code_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Code_Identifier__c</fullName>
    <description>identifier that can to used to indicate or locate the code that caused this logging item.</description>
    <label>Code Identifier</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Optional description of what this record is referring to</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Log_Item_Source__c.field-meta.xml
<CustomField>
    <fullName>Log_Item_Source__c</fullName>
    <description>Indicates where the System Log record originated from (inserted from)</description>
    <label>Log Item Source</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/task03-SystemLogDelete/classes/SYS_SystemLogDeleteBatchTest.cls
@isTest
public class SYS_SystemLogDeleteBatchTest {
    @isTest
    static void testBatchJob() {
        // Create test System_Log__c records
        List<System_Log__c> testLogs = new List<System_Log__c>();
        for (Integer i = 0; i < 2000; i++) {
            System_Log__c log = new System_Log__c(Code_Identifier__c='test',Description__c='test', Log_Item_Source__c ='test');
            testLogs.add(log);
        }
        insert testLogs;

        // Create an instance of the batch class
        SYS_SystemLogDeleteBatch batchJob = new SYS_SystemLogDeleteBatch(Date.today().addDays(-1), Date.today().addDays(1));

        // Start the batch job
        Test.startTest();
        Database.executeBatch(batchJob,2000);
        Test.stopTest();

        // Verify that the records were deleted
        List<System_Log__c> remainingLogs = [SELECT Id FROM System_Log__c];
        System.assertEquals(0, remainingLogs.size(), 'All System_Log__c records should have been deleted.');
    }
}