force-app/main/W-001393-Recall/objects/Recall_Item__c/Recall_Item__c.object-meta.xml
<CustomObject>
    <label>Recall Item</label>
    <nameField>
        <displayFormat>RI-{00000000}</displayFormat>
        <label>REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recall Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/W-001393-Recall/objects/Recall_Item__c/fields/Dealer_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Entity_Id__c</fullName>
    <label>Dealer Entity Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/W-001393-Recall/objects/Recall_Item__c/fields/Recall__c.field-meta.xml
<CustomField>
    <fullName>Recall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recall</label>
    <referenceTo>Recall__c</referenceTo>
    <relationshipLabel>Recall Items</relationshipLabel>
    <relationshipName>Recall_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/W-001393-Recall/objects/Recall_Item__c/fields/Recall_Account__c.field-meta.xml
<CustomField>
    <fullName>Recall_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recall Account</label>
    <referenceTo>Recall_Account__c</referenceTo>
    <relationshipLabel>Recall Items</relationshipLabel>
    <relationshipName>Recall_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/W-001393-Recall/objects/Recall_Item__c/fields/Recall_Model__c.field-meta.xml
<CustomField>
    <fullName>Recall_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recall Model</label>
    <referenceTo>Recall_Model__c</referenceTo>
    <relationshipLabel>Recall Items</relationshipLabel>
    <relationshipName>Recall_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/W-001393-Recall/objects/Recall_Model__c/Recall_Model__c.object-meta.xml
<CustomObject>
    <label>Recall Model</label>
    <nameField>
        <displayFormat>MODEL-{0000000}</displayFormat>
        <label>REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recall Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/W-001393-Recall/objects/Recall_Model__c/fields/Recall__c.field-meta.xml
<CustomField>
    <fullName>Recall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recall</label>
    <referenceTo>Recall__c</referenceTo>
    <relationshipName>Recall_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/W-001393-Recall/objects/Recall_Model__c/fields/Recall_Account__c.field-meta.xml
<CustomField>
    <fullName>Recall_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recall Account</label>
    <referenceTo>Recall_Account__c</referenceTo>
    <relationshipLabel>Recall Models</relationshipLabel>
    <relationshipName>Recall_Models</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/W-001393-Recall/classes/RecallAffectedUnitsBatch.cls
global with sharing class RecallAffectedUnitsBatch implements Database.Batchable<SObject> {
    public String query;
    private String recallId;
    public RecallAffectedUnitsBatch(String recallId) {
        this.recallId = recallId;
        // this.query = 'SELECT Id, Serial_Number__c, Model__c, Dealer_Entity_Id__c, Recall__c, Recall_Account__c, Recall_Model__c FROM Recall_Item__c WHERE Recall__c = '+ recallId;
    }

    global Iterable<SObject> start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, Serial_Number__c, Model__c, Dealer_Entity_Id__c, Recall__c, Recall_Account__c, Recall_Model__c FROM Recall_Item__c WHERE Recall__c = :this.recallId]);
        // return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<SObject> records) {
        // Create Missing Recall Accounts
        RecallHelper.createMissingRecallAccounts(this.recallId, records);
        // Relate wiht Recall Accounts
        RecallHelper.relateRecallItemsWithRecallAccounts(this.recallId, records);
        // Create Missing Recall Models
        RecallHelper.createMissingRecallModels(this.recallId, records);
        // Relate with Recall Models
        RecallHelper.relateRecallItemsWithModels(this.recallId, records);
        // Sum-Up the serial Numbers on Recall Models
        RecallHelper.sumUpRecallItemsSerialNumersToModels(this.recallId, records);
    }

    global void finish(Database.BatchableContext bc) {
    }
}