force-app/main/task05-LeadAss/objects/Postal_Code_Assignment__c/Postal_Code_Assignment__c.object-meta.xml
<CustomObject>
    <label>Postal Code Assignment</label>
    <nameField>
        <displayFormat>PCA-{000000}</displayFormat>
        <label>Postal Code Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Postal Code Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/task05-LeadAss/objects/Postal_Code_Assignment__c/fields/Pardot_Lead_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Pardot_Lead_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pardot Lead Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Postal_Code_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/task05-LeadAss/objects/Postal_Code_Assignment__c/fields/Pardot_Lead_Assignee_Name__c.field-meta.xml
<CustomField>
    <fullName>Pardot_Lead_Assignee_Name__c</fullName>
    <label>Pardot Lead Assignee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/task05-LeadAss/objects/Postal_Code_Assignment__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <externalId>true</externalId>
    <label>Postal Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/task05-LeadAss/classes/PostalCodeAssignmentTriggerTest.cls
@isTest
private class PostalCodeAssignmentTriggerTest {
    @isTest
    static void testPostalCodeAssignmentTrigger() {
        User us = [SELECT Id, Name FROM User WHERE IsActive = TRUE LIMIT 1];
        Postal_Code_Assignment__c pca1 = new Postal_Code_Assignment__c(Postal_Code__c = '00001', Pardot_Lead_Assignee_Name__c = us.Name);
        insert pca1;

        pca1 = [SELECT Id, Pardot_Lead_Assignee__c FROM Postal_Code_Assignment__c LIMIT 1];
        System.assertEquals(pca1.Pardot_Lead_Assignee__c, us.Id);
    }
}