force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/Data_Retention_Policy__c.object-meta.xml
<CustomObject>
    <label>Data Retention Policy</label>
    <nameField>
        <label>Data Retention Policy  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Retention Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/fields/Deletion_Logic__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Logic__c</fullName>
    <label>Deletion Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Delete</fullName>
            </value>
            <value>
                <fullName>Custom Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/fields/Handler_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Handler_Class_Name__c</fullName>
    <description>This is required is the Custom Deletion logic is selected.</description>
    <label>Handler Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Communication_Preference__c</fullName>
                <label>Communication Preference</label>
            </value>
            <value>
                <fullName>System_Log__c</fullName>
                <label>System Log</label>
            </value>
            <value>
                <fullName>LiveChatTranscript</fullName>
                <label>Chat Transcript</label>
            </value>
            <value>
                <fullName>NVM_VFPop</fullName>
            </value>
            <value>
                <fullName>REST Inbound Payload</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Order Products</fullName>
            </value>
            <value>
                <fullName>COM Order</fullName>
            </value>
            <value>
                <fullName>COM Order Item</fullName>
            </value>
            <value>
                <fullName>COM Order Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/fields/Retention_Time_Period__c.field-meta.xml
<CustomField>
    <fullName>Retention_Time_Period__c</fullName>
    <label>Retention Time Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <label>30 Days</label>
            </value>
            <value>
                <fullName>90</fullName>
                <label>90 Days</label>
            </value>
            <value>
                <fullName>180</fullName>
                <label>180 Days</label>
            </value>
            <value>
                <fullName>360</fullName>
                <label>1 Year</label>
            </value>
            <value>
                <fullName>720</fullName>
                <label>2 Years</label>
            </value>
            <value>
                <fullName>1080</fullName>
                <label>3 Years</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <label>5 Years</label>
            </value>
            <value>
                <fullName>3600</fullName>
                <label>10 Years</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/task3.01 - Storage - Data Ratention/classes/SYS_GenericRecordDeletionBatchScheduler.cls
global class SYS_GenericRecordDeletionBatchScheduler implements Schedulable {
    public Integer DEFAULT_BATCH_SIZE = 2000;
    public SYS_GenericRecordDeletionBatchScheduler(String query, Integer batchSize) {
    }

    global void execute(SchedulableContext sc) {
        List<Data_Retention_Policy__c> drps = [
            SELECT id, Name, Object__c, Deletion_Logic__c, Retention_Time_Period__c, Handler_Class_Name__c, is_Active__c
            FROM Data_Retention_Policy__c
            WHERE is_Active__c = TRUE
        ];

        SYS_GenericDeleteBatchHelper.runBatchJobs(drps, DEFAULT_BATCH_SIZE);
    }
}