force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/Data_Retention_Policy__c.object-meta.xml
<CustomObject>
    <label>Data Retention Policy</label>
    <nameField>
        <label>Data Retention Policy  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Retention Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/fields/Deletion_Logic__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Logic__c</fullName>
    <label>Deletion Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Delete</fullName>
            </value>
            <value>
                <fullName>Custom Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/fields/Handler_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Handler_Class_Name__c</fullName>
    <description>This is required is the Custom Deletion logic is selected.</description>
    <label>Handler Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Communication_Preference__c</fullName>
                <label>Communication Preference</label>
            </value>
            <value>
                <fullName>System_Log__c</fullName>
                <label>System Log</label>
            </value>
            <value>
                <fullName>LiveChatTranscript</fullName>
                <label>Chat Transcript</label>
            </value>
            <value>
                <fullName>NVM_VFPop</fullName>
            </value>
            <value>
                <fullName>REST Inbound Payload</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Order Products</fullName>
            </value>
            <value>
                <fullName>COM Order</fullName>
            </value>
            <value>
                <fullName>COM Order Item</fullName>
            </value>
            <value>
                <fullName>COM Order Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/task3.01 - Storage - Data Ratention/objects/Data_Retention_Policy__c/fields/Retention_Time_Period__c.field-meta.xml
<CustomField>
    <fullName>Retention_Time_Period__c</fullName>
    <label>Retention Time Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <label>30 Days</label>
            </value>
            <value>
                <fullName>90</fullName>
                <label>90 Days</label>
            </value>
            <value>
                <fullName>180</fullName>
                <label>180 Days</label>
            </value>
            <value>
                <fullName>360</fullName>
                <label>1 Year</label>
            </value>
            <value>
                <fullName>720</fullName>
                <label>2 Years</label>
            </value>
            <value>
                <fullName>1080</fullName>
                <label>3 Years</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <label>5 Years</label>
            </value>
            <value>
                <fullName>3600</fullName>
                <label>10 Years</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/task3.01 - Storage - Data Ratention/classes/SYS_GenericDeleteBatchHelper.cls
global with sharing class SYS_GenericDeleteBatchHelper {
    public static String JOB_EXECUTE_PERMISSION_NAME = 'Data_Retention_Batch_Job_Run';

    // These variables are used for UI initiated jobs
    public Id dataRetentionPolicyId { get; set; }
    public Data_Retention_Policy__c dataRetentionPolicy { get; set; }

    //constructor to get the recordId from UI
    public SYS_GenericDeleteBatchHelper(ApexPages.StandardController controller) {
        dataRetentionPolicy = (Data_Retention_Policy__c) controller.getRecord();
        dataRetentionPolicyId = dataRetentionPolicy.Id;
    }

    // the code can be executed from UI
    public PageReference runBatchJobFromUI() {
        system.debug('runBatchJobFromUI WORKS');
        runBatchJob(dataRetentionPolicyId);
        PageReference pageRef = new PageReference('/' + dataRetentionPolicyId);
        pageRef.setRedirect(true);
        return pageRef; //Returns to the case page
    }

    webService static void runBatchJob(Id dataRetentionPolicyId) {
        Data_Retention_Policy__c drp = [
            SELECT Id, Name, Object__c, Deletion_Logic__c, Retention_Time_Period__c, Handler_Class_Name__c, is_Active__c
            FROM Data_Retention_Policy__c
            WHERE Id = :dataRetentionPolicyId
        ];
        system.debug('runBatchJob works');
        runBatchJob(drp, 200);
    }

    public static void runAllDataRententionPolicyJobs(Integer batchSize) {
        List<Data_Retention_Policy__c> drps = [
            SELECT id, Name, Object__c, Deletion_Logic__c, Retention_Time_Period__c, Handler_Class_Name__c, is_Active__c
            FROM Data_Retention_Policy__c
            WHERE is_Active__c = TRUE
        ];
        runBatchJobs(drps, batchSize);
    }

    public static void runBatchJobs(Data_Retention_Policy__c[] drps, Integer batchSize) {
        for (Data_Retention_Policy__c drp : drps) {
            runBatchJob(drp, batchSize);
        }
    }

    public static void runBatchJob(Data_Retention_Policy__c drp, Integer batchSize) {
        if (!FeatureManagement.checkPermission(JOB_EXECUTE_PERMISSION_NAME)) {
            throw new CustomException('You do not have permission to execute this job');
        }

        if (drp.Deletion_Logic__c == 'Standard Delete') {
            SYS_GenericDeleteBatch batch = new SYS_GenericDeleteBatch(drp.Object__c, drp.Retention_Time_Period__c);
            Database.executeBatch(batch, batchSize);
            system.debug('DELETION BATCH JOB SET');
        } else {
            //  TODO run custom logic
        }
    }

    public class CustomException extends Exception {
    }
}